version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "8080:80"
    environment:
      - APP_ENV=production
      - APP_KEY=base64:YOUR_GENERATED_APP_KEY
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=your_database_name
      - DB_USERNAME=your_db_user
      - DB_PASSWORD=your_db_password

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: your_database_name
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: your_db_user
      MYSQL_PASSWORD: your_db_password
    ports:
      - "3306:3306"
